### ISSUE TITLE
运行第一个程序时出现了error

### ISSUE THREAD

**Issue by HideLakitu** [shujusenlin/mafengwo_data#1]
错误提示:
 File "D:/python_work/project/爬虫相关/旅游数据/获得城市数据.py", line 78, in <module>
    city_list = pd.read_excel('城市编号.xlsx')
这个我不太懂，好像是以excel格式读取时引发的，库的安装和import也没有问题，是什么导致的呢？

**Comment by HideLakitu** [comment]
没贴完:
Traceback (most recent call last):
  File "D:/python_work/project/爬虫相关/旅游数据/获得城市数据.py", line 78, in <module>
    city_list = pd.read_excel('城市编号.xlsx')
  File "D:\python_work\project\爬虫相关\练习\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "D:\python_work\project\爬虫相关\练习\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "D:\python_work\project\爬虫相关\练习\lib\site-packages\pandas\io\excel.py", line 307, in read_excel
    io = ExcelFile(io, engine=engine)
  File "D:\python_work\project\爬虫相关\练习\lib\site-packages\pandas\io\excel.py", line 354, in __init__
    raise ImportError(err_msg)
ImportError: Install xlrd >= 0.9.0 for Excel support

**Comment by Tony8005** [comment]
pip install xlrd
